// Code generated by bpf2go; DO NOT EDIT.
//go:build (386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64 || wasm) && linux

package main

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

// loadCorrelator returns the embedded CollectionSpec for correlator.
func loadCorrelator() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_CorrelatorBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load correlator: %w", err)
	}

	return spec, err
}

// loadCorrelatorObjects loads correlator and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*correlatorObjects
//	*correlatorPrograms
//	*correlatorMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadCorrelatorObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadCorrelator()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// correlatorSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type correlatorSpecs struct {
	correlatorProgramSpecs
	correlatorMapSpecs
	correlatorVariableSpecs
}

// correlatorProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type correlatorProgramSpecs struct {
	RecordConnect *ebpf.ProgramSpec `ebpf:"record_connect"`
	RecordExec    *ebpf.ProgramSpec `ebpf:"record_exec"`
	RecordOpen    *ebpf.ProgramSpec `ebpf:"record_open"`
}

// correlatorMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type correlatorMapSpecs struct {
	RingBuffer *ebpf.MapSpec `ebpf:"ring_buffer"`
}

// correlatorVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type correlatorVariableSpecs struct {
}

// correlatorObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadCorrelatorObjects or ebpf.CollectionSpec.LoadAndAssign.
type correlatorObjects struct {
	correlatorPrograms
	correlatorMaps
	correlatorVariables
}

func (o *correlatorObjects) Close() error {
	return _CorrelatorClose(
		&o.correlatorPrograms,
		&o.correlatorMaps,
	)
}

// correlatorMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadCorrelatorObjects or ebpf.CollectionSpec.LoadAndAssign.
type correlatorMaps struct {
	RingBuffer *ebpf.Map `ebpf:"ring_buffer"`
}

func (m *correlatorMaps) Close() error {
	return _CorrelatorClose(
		m.RingBuffer,
	)
}

// correlatorVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadCorrelatorObjects or ebpf.CollectionSpec.LoadAndAssign.
type correlatorVariables struct {
}

// correlatorPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadCorrelatorObjects or ebpf.CollectionSpec.LoadAndAssign.
type correlatorPrograms struct {
	RecordConnect *ebpf.Program `ebpf:"record_connect"`
	RecordExec    *ebpf.Program `ebpf:"record_exec"`
	RecordOpen    *ebpf.Program `ebpf:"record_open"`
}

func (p *correlatorPrograms) Close() error {
	return _CorrelatorClose(
		p.RecordConnect,
		p.RecordExec,
		p.RecordOpen,
	)
}

func _CorrelatorClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed correlator_bpfel.o
var _CorrelatorBytes []byte
